package org.sgx.j2s.utils.test;
/** this class was autogenerated from a .properties file by Properties2JavaBean */
public class ConfigBean{
	String serverUrl, password, username;
	public ConfigBean(String serverUrl, String password, String username){
		this.serverUrl=serverUrl;
		this.password=password;
		this.username=username;
	}
	public String getServerUrl(){
		return this.serverUrl;
	}
	public void setServerUrl(String attr){
		this.serverUrl = attr;
	}
	public String getPassword(){
		return this.password;
	}
	public void setPassword(String attr){
		this.password = attr;
	}
	public String getUsername(){
		return this.username;
	}
	public void setUsername(String attr){
		this.username = attr;
	}
	public static ConfigBean newInstante(){ 
		ConfigBean inst = new ConfigBean("http://192.168.1.111", "xyz", "fulano");;
		return inst;
	}
}